### ISSUE TITLE
Not receiving push notifications from freshChat

### ISSUE THREAD

**Issue by Shekhar7860** [freshworks/freshchat-android#101]
Not receiving push notifications from freshChat however receiving from firebase using same device token, check my payload - {"user":{"firstName":"Yantra","lastName":"Test Reseller","email":"testreseller@yantrait.co.uk","id":388643734462728,"alias":"c0d8f4ea-35e3-4264-a215-6a791687cbdb","groupAliasSet":[],"phone":"8837826904","phoneCountry":"+91","usage_meta":[],"kv_meta":[],"device_meta":[],"notificationId":"eiE1BZD9SSiCrLJE5tffiP:APA91bHnjs7QKjajb_HYJuIgELS0YvXMHYkr7EIOpBqfQ74QUQ-E68EZzxvi8C9_A02ch8Jz42-_IBwJRTL-VGtRgwY3HqA8tHnxHf6JuoRhyhkhJJ6LLaBV4N6ddxsLF5uZ_NQw7oMl","notificationType":1,"createdMillis":1597638924234,"updatedMillis":1597638924470,"type":0,"clientVersionCode":0,"clientType":0,"appId":0,"roleId":0,"experienceGroupId":0,"totalSessions":0,"deleted":0,"freshIdActivated":false,"lastSeenMillis":0,"present":false,"isNameGenerated":false,"usePriorityInbox":false,"activeForBillingCycle":false,"manuallyDeactivated":false,"dormantAgent":false,"liveTranslateEnabled":false,"isShadowBanned":false,"hardDeleted":false,"markedForDeletion":false,"isRbacForbidden":false,"jwtAuthStatus":0,"unsubscribedFromCampaign":false,"preview":false},"pushSuccessOnServer":true,"pushEnabled":true,"pushFailureReason":"Unknown","gcmNotificationResult":{"result":{"messageId":"0:1597639042285746%07385f2df9fd7ecd"}}}

**Comment by rameshfreshworks** [comment]
Hi @Shekhar7860 ,  The debug info posted above confirms that push has been successfully sent by freshchat server.  Please make sure that all received freshchat push messages are passed to freshchat SDK as shown in step 2 in [push notifications troubleshoot document](https://support.freshchat.com/en/support/solutions/articles/231986-android-push-notifications-are-not-working-how-do-i-fix-this-).

**Comment by sanketsingh12** [comment]
What do you mean??? if onMessageReceived is necessary?

**Comment by rameshfreshworks** [comment]
Yes, Inside the onMessageReceived() method of your FirebaseMessagingService extended class.
 ```
if (Freshchat.isFreshchatNotification(remoteMessage)) {

Freshchat.getInstance(this).handleFcmMessage(context, remoteMessage);

} else {

//Handle notifications with data payload for your app

}
```

**Comment by Shekhar7860** [comment]
but for firebase, its necessary i think? ok let me try...

**Comment by Shekhar7860** [comment]
Hello, what to do when the app is Closed...I am not getting notification at that time?

**Comment by rameshfreshworks** [comment]
Hi @Shekhar7860 , Notifications should work irrespective of the app state. Is this only happening for freshchat notifications or notifications in general ?

**Comment by Shekhar7860** [comment]
Yes it's only causing problem for fresh Chat notifications in android....

**Comment by rameshfreshworks** [comment]
Hi @Shekhar7860 , Can you check out our sample app and let us know if this is reproducible https://github.com/freshworks/freshchat-android/tree/master/Sample/FCPushNotificationSample/demo_app/src/main/java/com/example/demoapp

**Comment by Shekhar7860** [comment]
its android code, i want react native okk tell me what freshChatNotification - 0 means?

**Comment by MuthuFD** [comment]
Thanks for mentioning that you are using React Native Freshchat SDK.

When isFreshchatNotification returns 0, that means notification payload passed to freshchat SDK is not valid or not in expected format.

Freshchat SDK accepts payload in FCM format in Android and APNS formal in iOS.

If you are using any their party push handling libraries, they might be modifying the payload.
If you are using firebase library, check if `data` variable in payload contains payload in correct format, if so pass that value to Freshchat SDK.

Format are as follows.
**Android Push Payload Structure**
```
[
  {
    "channel_id": 570,
    "google.delivered_priority": "normal",
    "google.sent_time": 1563525214110,
    "google.ttl": 2419200,
    "google.original_priority": "normal",
    "app_id": 587545534469,
    "notif_type": 1,
    "msg_alias": "f863ff0d-52bf-4351-a8dd-f87064a107af",
    "source": "freshchat_user",
    "body": "afsd",
    "from": 20738924380,
    "timestamp": 1563525214100,
    "user_name": "Muthu krishnan",
    "google.message_id": "0:1563525214117672%07021d51f9fd7ecd",
    "target_user_alias": "df3596ee-f0d8-43b9-8148-a4dfcc511769",
    "conv_id": 248913951682272
  }
]
```
**iOS Push Payload Structure**
```
{
  "aps": {
    "alert": {
      "body": "message"
    },
    "badge": 1,
    "mutable-content": 1,
    "sound": "default"
  },
  "channel_id": 12,
  "conv_id": 248663974481425,
  "ephemeral": 0,
  "notif_type": 1,
  "source": "freshchat_user",
  "target_user_alias": "333487DA-467D-4F34-8EDB-78A498953528"
}
```

**Comment by Shekhar7860** [comment]
well, tell me from where i will get this payload??

**Comment by MuthuFD** [comment]
Payload is the data you received in push notification.
You would be passing it to `isFreshchatNotification`.

**Comment by Shekhar7860** [comment]
but, i m not receiving this push when app is closed? why?

**Comment by rameshfreshworks** [comment]
Hi @Shekhar7860 , Can you please share the code of your notification handling?

**Comment by Shekhar7860** [comment]
notification = () => {
    messaging().onMessage(async remoteMessage => {
      console.log('Message handled in the background!', remoteMessage);
      Freshchat.isFreshchatNotification(remoteMessage.data, (freshchatNotification) => {

      
              // console.log('fresh', freshchatNotification)
               if (freshchatNotification) {
                   Freshchat.handlePushNotification(remoteMessage.data);
               } else {
                   // handle your app notification
               }
           })
    });

**Comment by Shekhar7860** [comment]
notification = () => {
    messaging().onMessage(async remoteMessage => {
      console.log('Message handled in the background!', remoteMessage);
      Freshchat.isFreshchatNotification(remoteMessage.data, (freshchatNotification) => {

      
              // console.log('fresh', freshchatNotification)
               if (freshchatNotification) {
                   Freshchat.handlePushNotification(remoteMessage.data);
               } else {
                   // handle your app notification
               }
           })
    });

**Comment by MuthuFD** [comment]
@Shekhar7860 
When app is closed/killed, you need to handle push notification differently in `react-native-firebase`.
Please refer https://github.com/invertase/react-native-firebase/issues/1037

**Comment by Shekhar7860** [comment]
finally, i managed to get notification when app closed
