### ISSUE TITLE
Crash after open Image

### ISSUE THREAD

**Issue by amrsaiedcashu** [freshworks/freshchat-android#104]
I have three issues in SDK and I using the latest version 3.6.5
1- attach an image from the camera not work and make a crash
` java.lang.SecurityException: The authority of the uri content://com.example.demoapp.provider/external_cache/freshchat/tmp/JPEG_16001629642841989866830.jpg does not match the one of the contentProvider: com.cashu.app.uat.provider`
2- attached that attached from Gallay not shown in the chat 
3- Arabic layout direction not work fine

**Comment by MuthuFD** [comment]
@amrsaiedcashu 
1 & 2 : Can you share the code you have used for declaring provider in manifest and strings.xml
3: Please share us a screenshot of the issue

**Comment by amrsaiedcashu** [comment]
1-
`        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.example.demoapp.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/freshchat_file_provider_paths" />
        </provider>`

2-freshchat_file_provider_paths.xml
I used default and same crash 
`<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="external"
        path="." />
    <external-files-path
        name="external_files"
        path="." />
    <external-path
        name="external_files"
        path="." />

    <cache-path
        name="cache"
        path="." />
    <external-cache-path
        name="external_cache"
        path="." />
    <files-path
        name="files"
        path="." />

    <external-path
        name="files_root"
        path="Android/data/com.cashu.app.uat/" />

</paths>`

**Comment by MuthuFD** [comment]
1. Please share the code you have added in strings.xml for Freshchat provider
2. You need not modify freshchat_file_provider_paths.xml file. Its already present inside SDK.

**Comment by amrsaiedcashu** [comment]
١-    <string name="freshchat_file_provider_authority">com.example.demoapp.provider</string>
2- i replace it and same issue

**Comment by amrsaiedcashu** [comment]
<img width="379" alt="Screen Shot 2020-09-15 at 2 56 47 PM" src="https://user-images.githubusercontent.com/62697534/93213074-b5138600-f763-11ea-857e-22381c42a5f6.png">

**Comment by amrsaiedcashu** [comment]
1- now after capturing from camera return this error 
2- and from attachment make a white image but if click it's shown image

**Comment by MuthuFD** [comment]
2. Do not replace / edit / add freshchat_file_provider_paths.xml. Its already present inside SDK.
3. Is your device locale also Arabic? or Just App locale?

**Comment by amrsaiedcashu** [comment]
1- I am already do that and the same issue 
2- No, yes APP lang

**Comment by MuthuFD** [comment]
@amrsaiedcashu 
1. Please refer the sample app provided in this repo and try doing the same in your application.
2. Have implemented the steps to update runtime locale change section 7.4 from the integration documentation.
https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps

**Comment by amrsaiedcashu** [comment]
1- Same issue , it's library handle androidx.core.content.FileProvider

**Comment by amrsaiedcashu** [comment]
Exception on samsung SM-G925F Android API 7.0 (24) >>>>> Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.freshchat.consumer.sdk.i.a.doInBackground(Unknown Source)
        at com.freshchat.consumer.sdk.i.a.doInBackground(Unknown Source)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)

**Comment by MuthuFD** [comment]
@amrsaiedcashu Are you able to reproduce the issue in Sample app as well?
Irrespective of your response to previous question, Can you share us the sample app + code to support@freshchat.com. 
Our Support team will connect you with us. We can decide how to take this forward for a quicker resolution.

**Comment by rameshfreshworks** [comment]
Hi @amrsaiedcashu Hope your issue is resolved. If not, Please reach out to support@freshchat.com with sample app code using which we can reproduce the issue. Closing this now.
