### ISSUE TITLE
User properties don't accept something like "in-app-locale-code"

### ISSUE THREAD

**Issue by andreservidonigyg** [freshworks/freshchat-android#106]
Hello, i'm trying to add an user property but it keep receiving an error like this:
**2020-09-18 15:36:35.192 E: Key length exceeded for key: in-app-locale-code Limit is 32 characters. Key can only contain alphanumeric characters for key:in-app-locale-code (ErrorCode : 1000)**

Why is it not supported on Android? We used the SDK for iOS and works fine.
Thanks!

**Comment by MuthuFD** [comment]
@andreservidonigyg Thanks for pointing this out. We will get back to you with an update in the next 5 days.

**Comment by MuthuFD** [comment]
@andreservidonigyg We have fix this issue in the [latest version](https://github.com/freshworks/freshchat-android/releases/tag/3.6.6). Please update.
