### ISSUE TITLE
How to fully customize the layout of chat screen?

### ISSUE THREAD

**Issue by Punit-24** [freshworks/freshchat-android#107]
How to add padding to the AttachIcon, how to add an image of the user too like the image of the team member, how to change the style of the chat bubble,etc.......

**Comment by MuthuFD** [comment]
1. To change padding of Attach icon, add the below item in your dimen.xml and set your preferred value. Default padding is 10dp.
<dimen name="freshchat_message_attach_icon_padding">YOUR_PADDING_HERE</dimen>

2. how to add an image of the user too like the image of the team member?
Image is present only for Agent messages.

3. how to change the style of the chat bubble
You can provide your own 9patch images for chat bubbles. You can set them using styles.
These are the style keys freshchatChatBubbleLeft and freshchatChatBubbleRight.

Please refer documentation [here](https://support.freshchat.com/support/solutions/articles/229492-freshchat-android-sdk-themes-and-customizations) and customisation sample app [here](https://github.com/freshworks/freshchat-android/tree/master/Sample/FCCustomThemeSample)

**Comment by MuthuFD** [comment]
Hope your queries are resolved. Closing this issue.
If you are still having trouble, feel free to reopen this ticket or mail us at support@freshchat.com
