### ISSUE TITLE
App is crashing while opening freshchat in Android 10 

### ISSUE THREAD

**Issue by rituapplocum** [freshworks/freshchat-android#109]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alldaydr.patient.dev/com.freshchat.consumer.sdk.activity.ChannelListActivity}: android.view.InflateException: Binary XML file line #17 in com.alldaydr.patient.dev:layout/abc_screen_toolbar: Binary XML file line #17

**Comment by rameshfreshworks** [comment]
Hi @rituapplocum, Are you using this [calligraphy](https://github.com/chrisjenx/Calligraphy) library in the app? if yes, that is the reason for the crash on android 10. 
We recommend not to use the calligraphy library as it reached the end-of-it's-life as claimed in the repo.

**Comment by rituapplocum** [comment]
I resolved this issue
