### ISSUE TITLE
Freshchat Web Widget like UI customisation

### ISSUE THREAD

**Issue by congnq** [freshworks/freshchat-android#110]
Hi team, 
Can we customize the fresh chat sdk UI in Native or React Native to make it look like FreshChart in the web? 
on Mobile: 
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-11-02 at 11 37 13](https://user-images.githubusercontent.com/4245222/97830504-c7d81f00-1cff-11eb-8fcd-daa13245b63e.png)
on Web:
![Screen Shot 2020-10-31 at 14 04 46](https://user-images.githubusercontent.com/4245222/97830551-e3432a00-1cff-11eb-8632-9b317aa09868.png)
:
i found the [this document](https://developers.freshchat.com/web-sdk/), on web we have these config
```
config: {
      showFAQOnOpen: false,
      hideFAQ: false,
    }
```
When has these config, the SDK will showing up as my expectation(in website) but it's seems we don't have this config for FreshChat SDK on mobile. 

Thanks!

**Comment by MuthuFD** [comment]
Hi @congnq ,

We do not have web widget like layout for Mobile SDK.

Freshchat React Native SDK is a wrapper for Freshchat [Android](https://github.com/freshworks/freshchat-android) and [iOS](https://github.com/freshworks/freshchat-ios) SDKs.
So theme customisation has to be done in Android and iOS platform layer separately.

Android:
Documentation [here](https://support.freshchat.com/support/solutions/articles/229492-freshchat-android-sdk-themes-and-customizations).
Sample code [here](https://github.com/freshworks/freshchat-android/tree/master/Sample/FCCustomThemeSample).
iOS:
Documentation [here](https://support.freshchat.com/support/solutions/articles/229814-freshchat-ios-sdk-themes).

**Comment by congnq** [comment]
thank @MuthuFD for your answer

**Comment by dinhquan** [comment]
Hi @MuthuFD I know that we can customize the theme (change the font, color, background color, etc). But I wonder that with native customization if we can change the layout of UI on mobile (same exactly the web)?

**Comment by MuthuFD** [comment]
@dinhquan unfortunately thats not possible.

**Comment by dinhquan** [comment]
Thanks @MuthuFD
