### ISSUE TITLE
Access denied problem with implementating freshchat "Could not HEAD 'https://s3.amazonaws.com/moat-sdk-builds/com/github/freshdesk/freshchat-android/3.0.0/freshchat-android-3.0.0.pom'. Received status code 403 from server: Forbidden"

### ISSUE THREAD

**Issue by SalmaMau** [freshworks/freshchat-android#112]
I have been trying to implement freshchat in android studio and this is error i been getting " Could not HEAD 'https://s3.amazonaws.com/moat-sdk-builds/com/github/freshdesk/freshchat-android/3.0.0/freshchat-android-3.0.0.pom'. Received status code 403 from server: Forbidden" . Is there is a solution ?

**Comment by MuthuFD** [comment]
@SalmaMau Can you share us implementation for freshchat in your build.gradle?

In project level build.gradle, you need to add the following under dependencies.
`maven { url "https://jitpack.io" }`

In app module level build.gradle, you need to add the following.
`implementation 'com.github.freshdesk:freshchat-android:4.0.0'`

For more details refer this [link](https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps)

**Comment by SalmaMau** [comment]
buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
}
}

allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        flatDir {
            dirs 'libs'
        }
    }
}

// Android Resolver Repos Start
([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {

        maven {
            url "https://maven.google.com"
        }
       
        maven {
            url "https://maven.google.com" // Assets/GoogleAnalytics/Editor/GoogleAnalyticsDependencies.xml:34
        }
        maven {
            url "https://adcolony.bintray.com/AdColony" // Assets/GoogleMobileAds/Editor/AdColonyMediationDependencies.xml:7
        }
        maven {
            url "https://jcenter.bintray.com/" // Assets/GoogleMobileAds/Editor/AppLovinMediationDependencies.xml:7, Assets/GoogleMobileAds/Editor/FacebookMediationDependencies.xml:7, Assets/GoogleMobileAds/Editor/InMobiMediationDependencies.xml:7, Assets/GoogleMobileAds/Editor/MoPubMediationDependencies.xml:8, Assets/GoogleMobileAds/Editor/UnityMediationDependencies.xml:7
        }
        maven {
            url "https://maven.google.com/" // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
        }
        maven {
            url "https://jcenter.bintray.com" // Assets/GoogleMobileAds/Editor/VungleMediationDependencies.xml:7
        }
       
        maven {
            url "https://s3.amazonaws.com/moat-sdk-builds"
            content {
                includeGroupByRegex "com\\.moat.*"
            }
            // Assets/GoogleMobileAds/Editor/MoPubMediationDependencies.xml:8
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
}
// Android Resolver Repos End
apply plugin: 'com.android.library'


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.multidex:multidex:2.0.0'

        implementation ('com.google.firebase:firebase-inappmessaging-display:19.1.0')
        implementation ('com.google.android.gms:play-services-auth:18.0.0'){
            exclude(group: 'androidx.collection', module: 'collection')
        }
    implementation 'com.github.freshdesk:freshchat-android:3.0.0'
}

**Comment by MuthuFD** [comment]
@SalmaMau 

Below setup of yours is modifying the Freshchat SDK path
```
maven {
        url "https://s3.amazonaws.com/moat-sdk-builds"
        content {
            includeGroupByRegex "com\\.moat.*"
        }
        // Assets/GoogleMobileAds/Editor/MoPubMediationDependencies.xml:8
    }
```

This is the path for Freshchat pom file
`https://jitpack.io/com/github/freshworks/freshchat-android/4.0.0/freshchat-android-4.0.0.pom`

Please fix this. This will solve your issue.

**Comment by SalmaMau** [comment]
maven {
            url "https://jitpack.io/com/github"

            // Assets/GoogleMobileAds/Editor/MoPubMediationDependencies.xml:8
        }

i got Could not HEAD 'https://jitpack.io/com/github/com/github/freshdesk/freshchat-android/4.0.0/freshchat-android-4.0.0.pom'. Received status code 401 from server: Unauthorized

**Comment by rameshfreshworks** [comment]
Hope you were able to solve this issue.
If the problem still persists, Please reach out to us through support@freshchat.com
