### ISSUE TITLE
Problems in security audit using https://github.com/MobSF/Mobile-Security-Framework-MobSF

### ISSUE THREAD

**Issue by ankit010cse80** [freshworks/freshchat-android#113]
<img width="1056" alt="Screenshot 2020-11-09 at 5 40 08 PM" src="https://user-images.githubusercontent.com/3149460/98539606-a30d1a00-22b2-11eb-943a-0a69c3ecc6e5.png">

can anyone suggest what to do ? or any workaround ?

**Comment by rameshfreshworks** [comment]
Hi @ankit010cse80 , We no longer have the TaskAffinity set for any Freshchat activity. Please update to the latest SDK and check.

**Comment by ankit010cse80** [comment]
<img width="1027" alt="Screenshot 2020-11-11 at 11 21 21 AM" src="https://user-images.githubusercontent.com/3149460/98774008-1d06e580-2410-11eb-88c4-d8bca3e6e929.png">

will this also be fixed by latest SDK ?

**Comment by rameshfreshworks** [comment]
Hi @ankit010cse80, The Broadcast receivers mentioned are still declared in Manifest and being used. All the events registered are system events. This way of handling is necessary for Freshchat to function as expected.

**Comment by MuthuFD** [comment]
@ankit010cse80 Hope you got sufficient clarifications.
If you need more clarity, please reach out to us at support@freshchat.com
