### ISSUE TITLE
Deploy to mavenCentral

### ISSUE THREAD

**Issue by tasomaniac** [freshworks/freshchat-android#115]
Please consider deploying to mavenCentral next to Jitpack. Jitpack is not really reliable and is slow. Deploying to mavenCentral will make the library download more reliable.

**Comment by MuthuFD** [comment]
@tasomaniac 
Can you tell us some of the issues which you have faced with the current approach and how you have solved those?

**Comment by tasomaniac** [comment]
Jitpack servers can be down time to time. Even though this is rare, it creates a big issue when happens.

I'm also not saying to remove from Jitpack. That should be kept.

I'm just requesting to deploy to maven Central too since that one is more reliable. 

Thanks

**Comment by rameshfreshworks** [comment]
We have informed our product team regarding this request.
You can reach out to us through support@freshchat.com for further queries.
