### ISSUE TITLE
Android push notification not working

### ISSUE THREAD

**Issue by RMVIVEK55** [freshworks/freshchat-android#117]
1.override fun onNewToken(p0: String) {
        Log.e("FB token",p0)

        super.onNewToken(p0)
        Freshchat.getInstance(this).setPushRegistrationToken(p0)
    }

----------------------------------------------------------------------------------------------
2.override fun onMessageReceived(p0: RemoteMessage) {
        super.onMessageReceived(p0)
        Log.e("notification1", p0.toString())//empty
        if (Freshchat.isFreshchatNotification(p0)) {
            Freshchat.handleFcmMessage(this, p0);
            Log.e("notification1", p0.toString())
        }
--------------------------------------------------------------------------------------------------------
my moblie pie

**Comment by rameshfreshworks** [comment]
Hi @RMVIVEK55 , Refer this [troubleshooting](https://support.freshchat.com/en/support/solutions/articles/231986-android-push-notifications-are-not-working-how-do-i-fix-this-) document to fix this issue.

**Comment by RMVIVEK55** [comment]
![noti](https://user-images.githubusercontent.com/55997245/102874287-43389000-4468-11eb-8423-7e243d890f9b.png)

**Comment by RMVIVEK55** [comment]
@rameshfreshworks I had to enable push notification

**Comment by rameshfreshworks** [comment]
Check the following steps 
1.  Check if you've saved the right FCM key in Freshchat Admin( gear icon) > Mobile SDK -> FCM Server API Key (Android) input field.  if not update FCM server key here.
2.  After executing the above steps if you are not receiving notifications take the conversation ID from the URL. It would be the last 10 or more digits. Paste it at the following URL:

https://web.freshchat.com/app/api/notif_debug?convId=<conv-id-value-here>

hit the above url and send the response.

**Comment by RMVIVEK55** [comment]
After added the firebase key I got a notification. Thanks. @rameshfreshworks
