### ISSUE TITLE
I cannot view addition information

### ISSUE THREAD

**Issue by RMVIVEK55** [freshworks/freshchat-android#118]
![add](https://user-images.githubusercontent.com/55997245/102883552-358a0700-4476-11eb-8eea-219889c6a453.png)

  val customerinfoobject = pickMeLocals.getCustomerSharedInfo()
val freshchatUser = Freshchat.getInstance(applicationContext).user
        freshchatUser.firstName = customerinfoobject.Customer_First_Name
        freshchatUser.lastName = customerinfoobject.Customer_Last_Name
        freshchatUser.email = customerinfoobject.Customer_Email_Address

        freshchatUser.setPhone("+91", customerinfoobject.Customer_Mobile_Number.toString())

        Freshchat.getInstance(getApplicationContext()).setUser(freshchatUser);

        Freshchat.getInstance(applicationContext).user = freshchatUser
        Freshchat.getInstance(getApplicationContext()).identifyUser(customerinfoobject.Customer_Email_Address!!, null);
        val restoreId = Freshchat.getInstance(applicationContext).user.restoreId
        val d = Freshchat.FRESHCHAT_USER_RESTORE_ID_GENERATED
        Log.e("restoreId", restoreId + "--_______--" + d)
      
        val eventName = "Visited Order Details page"

        var userID = SharedPreferenceUtils.getString(MyPreferences.UserID)
        val freshchatUser1 = Freshchat.getInstance(applicationContext).user
        val properties: HashMap<String, Any> = HashMap()
        properties.put("From_Id", userID!!)
        properties.put("To_Id", AdminID)

        properties.put("firstName", customerinfoobject.Customer_First_Name!!)
        properties.put("lastName", customerinfoobject.Customer_Last_Name!!)
        properties.put("email", customerinfoobject.Customer_Email_Address!!)
        properties.put("Phone", "+91" + customerinfoobject.Customer_Mobile_Number.toString())
        properties.put("Store_Name", "Gaja")
        
           Freshchat.trackEvent(this, eventName, properties);

img_send.setOnClickListener {

            Freshchat.showConversations(getApplicationContext());

        }

**Comment by RMVIVEK55** [comment]
If am using only trackEvent  means i cannot view Email,Phone

**Comment by rameshfreshworks** [comment]
Hi @RMVIVEK55 , 
Email and phone number are user properties. You need to update these using following API as you are doing in above code.
Freshchat.getInstance(getApplicationContext()).setUser(freshchatUser);

**Comment by RMVIVEK55** [comment]
@rameshfreshworks I can't view  user property
val freshchatUser1 = Freshchat.getInstance(applicationContext).user
    val properties: HashMap<String, Any> = HashMap()
    properties.put("From_Id", userID!!)
    properties.put("To_Id", AdminID)

    properties.put("firstName", customerinfoobject.Customer_First_Name!!)
    properties.put("lastName", customerinfoobject.Customer_Last_Name!!)
    properties.put("email", customerinfoobject.Customer_Email_Address!!)
    properties.put("Phone", "+91" + customerinfoobject.Customer_Mobile_Number.toString())
    properties.put("Store_Name", "Gaja")
    
       Freshchat.trackEvent(this, eventName,

**Comment by rameshfreshworks** [comment]
Freshchat.trackEvent(this, eventName, properties) is used to track user events. Tracked events are listed under **Events Timeline** in the right pane(scroll down a bit to see this). 

If you want to store the above values as user properties ,use the following API
Freshchat.getInstance(getApplicationContext()).setUserProperties(properties);

These values displayed under **User Properties** above Events Timeline on the right pane.

**Comment by RMVIVEK55** [comment]
val customerinfoobject = pickMeLocals.getCustomerSharedInfo()
        val freshchatUser = Freshchat.getInstance(applicationContext).user
        freshchatUser.firstName = customerinfoobject.Customer_First_Name
        freshchatUser.lastName = customerinfoobject.Customer_Last_Name
        freshchatUser.email = customerinfoobject.Customer_Email_Address

        freshchatUser.setPhone("+91", customerinfoobject.Customer_Mobile_Number.toString())

        Freshchat.getInstance(getApplicationContext()).setUser(freshchatUser);

        Freshchat.getInstance(applicationContext).user = freshchatUser
        Freshchat.getInstance(getApplicationContext()).identifyUser(customerinfoobject.Customer_Email_Address!!, null);
        val restoreId = Freshchat.getInstance(applicationContext).user.restoreId
        val d = Freshchat.FRESHCHAT_USER_RESTORE_ID_GENERATED
        Log.e("restoreId", restoreId + "--_______--" + d)
       
        val eventName = "Visited Order Details page"

        var userID = SharedPreferenceUtils.getString(MyPreferences.UserID)
        val freshchatUser1 = Freshchat.getInstance(applicationContext).user
        val properties: HashMap<String, Any> = HashMap()
        properties.put("From_Id", userID!!)
        properties.put("To_Id", "AdminID")

        properties.put("firstName", customerinfoobject.Customer_First_Name!!)
        properties.put("lastName", customerinfoobject.Customer_Last_Name!!)
        properties.put("email", customerinfoobject.Customer_Email_Address!!)
        properties.put("Phone", "+91" + customerinfoobject.Customer_Mobile_Number.toString())
        properties.put("Store_Name", "Gaja")

           Freshchat.trackEvent(this, eventName, properties);

@rameshfreshworks   I have event property but I cannot show right side penal


![user](https://user-images.githubusercontent.com/55997245/103008089-925eed80-455a-11eb-90d8-7308f3beabea.png)

**Comment by RMVIVEK55** [comment]
and location place is incorrect am send message from arani near vellore but is show kerala. Am in Tamilnadu

**Comment by rameshfreshworks** [comment]
Looks like you have lot of queries. We have a support team to handle these queries. Please send an email to support@freshchat.com or chat from your Freshchat account. This way you can get your queries answered quickly.

**Comment by RMVIVEK55** [comment]
@rameshfreshworks Just tell me how i can view web postal event property

String eventName = "Visited Order Details page";

// Create a map and set required properties like below  
HashMap<String, Object> properties = new HashMap<>();
properties.put("Order Id", 3223232332);
properties.put("Order Date", "24 Jan 2020");
properties.put("Order Status ", "In-Transit");

// Call trackEvent by passing eventName and a map of properties
Freshchat.trackEvent(getContext(), eventName, properties);

**Comment by MuthuFD** [comment]
You can find events in user's event's timeline

@RMVIVEK55 hope you are able got your queries cleared.
If you have more queries, feel free to reach us at support@freshchat.com
