### ISSUE TITLE
Location incorrectly show

### ISSUE THREAD

**Issue by RMVIVEK55** [freshworks/freshchat-android#120]
![location](https://user-images.githubusercontent.com/55997245/103010426-5c236d00-455e-11eb-8f39-38551bebb2da.png)

Am sent the message from arani tamilnadu but portal side it show kerala location

**Comment by RMVIVEK55** [comment]
![add](https://user-images.githubusercontent.com/55997245/103010593-8d9c3880-455e-11eb-927b-c3c7f8e32346.png)
Am send the message from chennai it show correct send location but arani in correctly

**Comment by RMVIVEK55** [comment]
How to fix

**Comment by rameshfreshworks** [comment]
The location mapping is based on the IP address. This data mostly helps us to find out the users on country level. We use third party service for this and it is not reliable to get the exact location.

**Comment by RMVIVEK55** [comment]
so, its issue right @rameshfreshworks

**Comment by MuthuFD** [comment]
@RMVIVEK55 We do not guarantee that the location is exact. We update the IP mapping on a monthly basis.
If you want exact data, I would suggest you to use Android Location services and log user location as a user property.
