### ISSUE TITLE
User Restore broadcast is never received in Europe

### ISSUE THREAD

**Issue by tasomaniac** [freshworks/freshchat-android#121]
## Describe the bug

We started to get bug reports saying that Freshchat is not visible (mostly from European region).

I checked with different environments in our app. In Japan, it works correctly. 

For user registration, we set the properties and wait for `com.freshchat.consumer.sdk.UserRestoreIdGenerated` BroadcastReceiver to be triggered. In European region, it is not triggered.

## Platform
- [x] Android
- [ ] React Native

## Freshchat SDK version
- SDK version : 4.2.0

## Device information
- [X] is reproducible on all devices? 
Yes

**Comment by rameshfreshworks** [comment]
Hi @tasomaniac , We had an incident of degraded performance in EU region. It is resolved now.  Please let us know, if the users are still experiencing this issue. Ref : https://status.freshchat.com/incident/29914

**Comment by tasomaniac** [comment]
Hey, I was just sending another email to support. 

Unfortunately, we still have this issue. And it happens only in Europe.

**Comment by rameshfreshworks** [comment]
Hi @tasomaniac ,
We hope this issue is resolved now. If not feel free to reopen or contact us by emailing support@freshchat.com.

**Comment by tasomaniac** [comment]
Hi specific issue in Europe is resolved. But the technical issue is still there.

When we restore the user, we only have the option to register broadcast receiver for success. If any error happens on Freshchat side, we are never notified. 

Is it possible to introduce registering another callback to receive error messages?

**Comment by MuthuFD** [comment]
@tasomaniac Right now we do not have an event for Restore failures.
Thanks for showing the need for this. 
I will keep you posted on any development in this area.

**Comment by tasomaniac** [comment]
Any ticket that we can follow to get updates on this?
