### ISSUE TITLE
Back Icon color Not changing in Action Bar

### ISSUE THREAD

**Issue by harisraza123** [freshworks/freshchat-android#125]
In Freshchat UI Customization Backarrow Color is not Changing

**Comment by MuthuFD** [comment]
@harisraza123 please share the UI customisation you have tried to change backarrow.

**Comment by harisraza123** [comment]
<style parent="@style/Base.Widget.AppCompat.ActionBar" name="MyCustomTheme.ActionBarStyle">
        <item name="titleTextStyle">@style/ActionBarTitleText</item>
        <item name="subtitleTextStyle">@style/ActionBarSubTitleText</item>
        <item name="actionButtonStyle">@style/ActionBArActionStyle</item>
        <item name="background">@drawable/action_bar_background</item>
    </style>

    <style parent="Base.Widget.AppCompat.ActionButton" name="ActionBArActionStyle" >
        <item name="android:color">#000000</item>
    </style>

**Comment by harisraza123** [comment]
Can you gide me house to change the back Arrow color i can Customize the whole Action Bar But unable to Customize the back arrow Color.

**Comment by rameshfreshworks** [comment]
Setting `toolbarNavigationButtonStyle` will get it work. Find the sample code below    


    <style name="Theme.Freshchat.SelectedTheme" parent="CustomAppTheme" />

    <style name="CustomAppTheme" parent="Theme.Freshchat.Light.DarkActionBar">
       
        // Code to change navigtion button style
        <item name="toolbarNavigationButtonStyle">@style/Toolbar.Button.Navigation.Tinted</item>
     </style>

    <style name="Toolbar.Button.Navigation.Tinted" parent="Widget.AppCompat.Toolbar.Button.Navigation">
        <item name="tint">COLOR_VALUE</item>
    </style>

**Comment by rameshfreshworks** [comment]
Hope this issue is resolved. Closing the issue. Feel free to reopen this issue or reach out to support@freshchat.com in case the issue still persists.
