### ISSUE TITLE
Override link handling

### ISSUE THREAD

**Issue by yasirtrimulabs** [freshworks/freshchat-android#126]
## Description
I am trying to override the default external link click behaviour currently on react native. 
I have tried this method from the [RN documentation](https://www.npmjs.com/package/react-native-freshchat-sdk):

![Screenshot 2021-01-27 at 4 07 50 PM](https://user-images.githubusercontent.com/62023757/105982951-d2654300-60b9-11eb-8189-4ff2bdaf76d6.png)

Above method is working in iOS but not on the Android side. So I decided to try it in native Android.
Tried this method from [Android SDK documentation](https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps):

![Screenshot 2021-01-27 at 4 11 06 PM](https://user-images.githubusercontent.com/62023757/105983255-469fe680-60ba-11eb-8edc-68bb646aca1f.png)

But still it's not working. So after further digging I found this [Track event documentation](https://support.freshchat.com/support/solutions/articles/50000000057-how-to-track-user-actions-happening-inside-freshchat-sdk):

![Screenshot 2021-01-27 at 4 12 53 PM](https://user-images.githubusercontent.com/62023757/105983394-849d0a80-60ba-11eb-988b-86e0ba52a5ba.png)

But still I am stuck. Can someone guide me? 

## Freshchat SDK version
- React Native SDK version: 3.1.1 
- React Native version: 0.63.2

**Comment by rameshfreshworks** [comment]
Hi @yasirtrimulabs, The first approach is the recommended one. Can you let us know for which link this is not working?

**Comment by hakeemsyd** [comment]
I have tried
google.com
www.google.com
https://google.com
https://www.google.com
But nothing works

**Comment by yasirtrimulabs** [comment]
Hi @rameshfreshworks so far I have tried these
google.com
www.google.com
https://google.com
https://www.google.com
But nothing works on android

**Comment by MuthuFD** [comment]
@yasirtrimulabs 
We tested this from ourside.
We are able to verify that we are able to listen to non-freshchat links.

Please place the below code in App.js and try.
```
componentDidMount() {
  Freshchat.addEventListener(
    Freshchat.EVENT_EXTERNAL_LINK_CLICKED,
    openLinkHandler
  );
}

const openLinkHandler = (data) => {
    console.log("openLinkHandler triggered - ", data);
};
```

If you still facing issues, we recommend you to share a sample app where you can reproduce this issue and reopen this issue.
You can also reach out to use through support@freshchat.com

**Comment by yasirtrimulabs** [comment]
@MuthuFD I have reached to support already. 
I send a link in a FAQ and it's working but not for a link sent in chat.
