### ISSUE TITLE
Need way to embed FC UI in React Native parent view

### ISSUE THREAD

**Issue by ajp8164** [freshworks/freshchat-android#127]
## Problem Description
> Using the react-native-freshchat-sdk.

With reference to [37](https://github.com/freshworks/freshchat-android/issues/37) - I have a requirement to place the FC view inside a parent. 

## Describe the solution
Need a way to embed FC in a parent  view in React Native app.

**Is there a way to do this within a React Native app?**

**Comment by rameshfreshworks** [comment]
We have informed our product team regarding this request.
You can reach out to us through support@freshchat.com for further queries.
