### ISSUE TITLE
Push Notification and Unread count is not working 

### ISSUE THREAD

**Issue by puliajay43** [freshworks/freshchat-android#128]
## Push Notification and Unread count is not working 
I have integrated the Push Notification and Unread count as in Documentation. But It didn't worked as expected.
In the Inbox, I am getting **Push Notification Enabled** is true.
<img width="285" alt="Screenshot 2021-02-17 at 9 44 14 PM" src="https://user-images.githubusercontent.com/35003996/108232947-4cdd2c00-7169-11eb-856f-a66f55062518.png">

I have tried adding the FCM token in web. But there is an issue on saving the FCM Token
<img width="399" alt="Screenshot 2021-02-17 at 9 18 10 PM" src="https://user-images.githubusercontent.com/35003996/108230094-68930300-7166-11eb-8b84-53760d6ba720.png">

## Expected behavior
I want to get Push notification and Update the Unread count while App is Foreground, Background and Killed State
## Platform
- [x] Android

## Freshchat SDK version
- SDK version : 4.3.0

## Device information
- reproducible on all devices

**Comment by MuthuFD** [comment]
@puliajay43 Please make sure that you are uploading **FCM server key** here.
Server key is available in Firebase console under **Project Settings -> Cloud Messaging -> Project Credentials**

**Comment by MuthuFD** [comment]
If you are getting the same error even after providing correct server key, please contact us using support@freshchat.com
