### ISSUE TITLE
SendMessage fails on fresh install

### ISSUE THREAD

**Issue by ishaansrm** [freshworks/freshchat-android#132]
## Describe the bug
When trying to use `.sendMessage()` API in android SDK, after a fresh install, it fails with this message in the logcat

`W/FRESHCHAT: Could not send message to channel filtered by tag => null`

Subsequent `sendMessage()` requests work after opening freshchat via `.showConversations()` but the first one after a fresh install doesn't work.

We are initializing the SDK in onCreate() of MainActivity which is called way before we try to send this message in a different activity.

Code:
```
FreshchatMessage FreshchatMessage = new FreshchatMessage().setMessage(automatedChatMsg);
Freshchat.sendMessage(getApplicationContext(), FreshchatMessage);
Freshchat.showConversations(this);
```

## Steps to reproduce
* Do a fresh install of the app
* use `sendMessage()` api to send a message with or without any tags
* Message is not sent & warning appears in logcat

## Expected behavior
Message should be sent in the default inbox topic & be visible in chats & on freshchat portal

## Freshchat SDK version
- SDK version : 3.6.7

## Device information
- [x] is reproducible on all devices? 

Provide device details here like
 * Device name: Samsung Galaxy Note 9 & Emulators
 * OS version: Android 10 & 11

**Comment by rameshfreshworks** [comment]
@ishaansrm  Need to pass tag value as part of the Freshchat message to get this work. 
Refer section 5 in [documentation](https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps).

**Comment by ishaansrm** [comment]
That's what I had originally tried but same warning comes in logcat

`W/FRESHCHAT: Could not send message to channel filtered by tag => my_tag_name`

I thought maybe the topics are loaded onto the local db only after the chat window opens so lemme try to send msgwithout tags, but that wasn't working either.

Even waiting for more than 2mins after frshchat init the sendMessage API doesn't work, until freshchat screen is loaded via showConversations()

**Comment by rameshfreshworks** [comment]
@ishaansrm Okay. 
Freshchat SDK loads configured data from server during first init. Usually this takes few seconds. i believe this could be the reason. 
We suggest you to do the Freshchat.init() in application class and see.

**Comment by ishaansrm** [comment]
Tried Freshchat.init() in application class but that didn't work either. Tried to wait for 2mins after init() call but still sendMessage failed, multiple times. 

What works as a workaround is calling showConversations() to open chat, and then via a handler delay the sendMessage( ) api by 1sec. Then it works everytime, even on fresh installs.

```
Freshchat.showConversations(this);
new Handler().postDelayed({
    FreshchatMessage FreshchatMessage = new FreshchatMessage().setMessage(automatedChatMsg);
    Freshchat.sendMessage(getApplicationContext(), FreshchatMessage);
}, 1000);
```

**Comment by rameshfreshworks** [comment]
Hey @ishaansrm, please reach out to support@freshchat.com. We will take it from there.
