### ISSUE TITLE
Resolution confirmation prompt title is not visible

### ISSUE THREAD

**Issue by nikoker** [freshworks/freshchat-android#134]
## Describe the bug
The resolution confirmation prompt title view is not visible at all. The 2 buttons Yes and No are visible but the title itself is missing.

## Steps to reproduce
```    
* Step 1 - Start a conversation with our support team
* Step 2 - Our support agent marks the conversation as resolved
* Step 3 - The resolution prompt appears but the title is missing. Please see screenshots below.
```

## Expected behavior
Resolution confirmation prompt title text view should appear.

## Platform
- [ ] Android Occurs in production for many users. Tested on our side with Android 11

## Freshchat SDK version
- SDK version : 4.3.3

## Device information
- [ ] is reproducible on all devices? 

```
Provide device details here like
 * Device name
 * OS version

```

## Screenshot/ Video recording 
<img width="1112" alt="Screenshot 2021-04-15 at 16 31 01" src="https://user-images.githubusercontent.com/7926991/114889675-9add7b80-9e0a-11eb-8b17-d43a696e79e1.png">

![Screenshot_20210415-164222](https://user-images.githubusercontent.com/7926991/114891222-fc521a00-9e0b-11eb-9713-2bee8144c96e.png)

As you can see, I troubleshot the issue with the layout inspector and it turns out that the text is empty which explains why the textView is not visible to the users.
We are overriding the strings for this feature:

```
  <!-- Freshchat -->
  <string name="freshchat_chat_resolution_confirmation_prompt">Did we address your concerns?</string>
  <!-- Freshchat -->
  <string name="freshchat_chat_resolution_confirmation_prompt_negative">No</string>
  <!-- Freshchat -->
  <string name="freshchat_chat_resolution_confirmation_prompt_positive">Yes</string>
```

**Comment by rameshfreshworks** [comment]
Hi @nikoker, 
Are you defining these overridden strings in your app module strings.xml file?

**Comment by nikoker** [comment]
Hey @rameshfreshworks , yes, look at my post above. I am mentioning this at the end.

**Comment by rameshfreshworks** [comment]
@nikoker Can you try reproduce this in the following sample app and send us code with your customization's? 
https://github.com/freshworks/freshchat-android/tree/master/Sample/FreshchatSample

**Comment by nikoker** [comment]
How can I mark the conversation as resolved with your sample?

**Comment by nikoker** [comment]
I found out what the issue was. We were wrongly overriding the style that was used for this view. Thanks for your time.
