### ISSUE TITLE
how to change the tea member message background color and also chat background image

### ISSUE THREAD

**Issue by mm7mod** [freshworks/freshchat-android#135]
hello , 

I have a question, now with the below documentation we can change many aspects of the freshchat :
https://support.freshchat.com/support/solutions/articles/229492-freshchat-android-sdk-themes-and-customizations

however two stuff I didn't know how to change their color : 

1- first we can see that the team-member chat message background color is "light blue", how can I change this color 
2- also the chat background has a type of image pattern how can I change this also 

![android ](https://user-images.githubusercontent.com/46278471/116797978-87f5c700-aaeb-11eb-9af4-1968da78fbbc.jpg)

**Comment by mm7mod** [comment]
for the chat background color I managed to chat it instead of the pattern :

 <item name="freshchatMessageListStyle">@style/freshchatMessageListStyleCustom</item>
....
   <style name="freshchatMessageListStyleCustom" parent="Widget.Freshchat.MessageList">
        <item name="android:background">@color/freshchat_white</item>
    </style>


######################
I still have problems with this : 

1- first we can see that the team-member chat message background color is "light blue", how can I change this color

**Comment by MuthuFD** [comment]
Chat bubbles are drawables. If you want to change them, you need to replace the existing drawable with your own drawable.

Key to update is freshchatChatBubbleLeft

For more details refer section "2.3 Drawable and Icons" in documentation.
