### ISSUE TITLE
incoming messages take long time to show for customers on android/react native app

### ISSUE THREAD

**Issue by mm7mod** [freshworks/freshchat-android#136]
https://user-images.githubusercontent.com/46278471/116801629-e0d55780-ab0b-11eb-8d48-cc714db5f9db.mp4

## Describe the bug
-- I have an android/react native app that  I want to add and chat functionality to it and to integrate it with freshchat 
-- incoming messages take a long time to show for customers on android/react native app and I have tested on , real mobile device for both react native and android separately and also on the android studio device and I got the same pattern . 
-- here attached a video recording on the issue I am having 

## Steps to reproduce

-- deploying a simple freshchat android/react native app : 
https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps

-- when the customer sends a message, it shows up immediately in the inbox for the agent to reply 
-- when the agent sends a reply to the customer it takes between 13-25 seconds for the chat messages list to update the incoming message which is a very long time.

-- my internet connection is fast so this is not a connection issue 
-- also when integrating with push notifications, I receive the notification almost immediately to my device, but the messages in the chat list itself would take another 8-20 seconds to reflect that. 

## Expected behavior
I am expecting that the chat list to get updated quickly and for the messages not to show up after 13-25 seconds which is not the best-expected behavior for real-time chatting 

## Platform
- [ ] Android
- [ ] React Native

## Freshchat SDK version
- SDK version: using latest available version 4.3.3 
- React Native version (if applicable) : 
"react-native": "0.64.0"

## Device information
-- I tested on Samsung A20 device and also the emulator 

## Screenshot/ Video recording 
https://user-images.githubusercontent.com/46278471/116801629-e0d55780-ab0b-11eb-8d48-cc714db5f9db.mp4

**Comment by MuthuFD** [comment]
@mm7mod From the video recording, I can see that push notifications is not integrated. 

When user is present inside chat, messages are updated in 2 ways.

1. As soon as the Freshchat new message push notification is received
2. SDK polls for new messages at regular intervals. Interval varies from 20s to 60s. Interval depends on the result of the previous message update request.
If you are seeing delays in message update, that means messages are updated using polling and not push notifications.

To integrate push notification, Refer Push notification section in integration details.

If you have integrated push notification and still messages are updated with a delay, then integration is not successful.

Please contact support team for push notification troubleshooting documentation.
