### ISSUE TITLE
Android 4.4: Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sprent.customer.staging/com.freshchat.consumer.sdk.activity.ConversationDetailActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class ImageView

### ISSUE THREAD

**Issue by SerhiiSolobaievUptech** [freshworks/freshchat-android#19]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sprent.customer.staging/com.freshchat.consumer.sdk.activity.ConversationDetailActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by tryprasannan** [comment]
@SerhiiSolobaievUptech Are you customizing and specifying vector drawable for any icon in Freshchat ?
If yes, can you share the vector drawable and target OS version and appcompat and vector compat lib versions?

**Comment by SerhiiSolobaievUptech** [comment]
@tryprasannan Yes, I set vector drawable to the `freshchatSendIcon` style item.
Target OS: Android 4.4
AppCompat lib: com.android.support:appcompat-v7:27.1.1
VectorCompat lib: not used. I've set `vectorDrawables.useSupportLibrary = true` in build.gradle and using app:srcCompat in xmls  to set vector drawables.
Drawable:
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0">
    <path
        android:fillColor="#ffe100"
        android:pathData="M2.01,21L23,12 2.01,3 2,10l15,2 -15,2z"/>
</vector>`

**Comment by deathstroke007** [comment]
Getting the same error.

I am changing the style for particular activity like this in AndroidManifest.xml

```
<activity
            android:name="com.freshchat.consumer.sdk.activity.ChannelListActivity"
            android:theme="@style/freshchattheme"
            tools:replace="android:theme" />

        <activity
            android:name="com.freshchat.consumer.sdk.activity.ConversationDetailActivity"
            android:theme="@style/freshchattheme"
            tools:replace="android:theme" />
```

@style/freshchattheme

```
<style name="freshchattheme" parent="Theme.AppCompat.Light.DarkActionBar">

        <item name="android:listDivider">@color/white_pressed</item>
        <item name="colorPrimary">@color/white</item>
        <item name="android:textColor">#212121</item>
        <item name="android:colorAccent">@color/colorAccent</item>
        <item name="colorControlActivated">@color/colorAccent</item>
        <item name="android:windowDisablePreview">true</item>
        <item name="android:windowAnimationStyle">@null</item>
        <item name="android:itemBackground">#ffffff</item>
        <!--<item name="actionMenuTextColor">#212121</item>-->
        <item name="android:letterSpacing">0.03</item>
        <!--<item name="android:statusBarColor">#CCCCCC</item>
        <item name="android:colorPrimaryDark">#CCCCCC</item>-->
        <item name="android:windowLightStatusBar">true</item>

    </style>
```

> Unable to start activity ComponentInfo{com.khaalijeb.inkdrops.debug/com.freshchat.consumer.sdk.activity.ConversationDetailActivity}: android.view.InflateException: Binary XML file line #44: Binary XML file line #7: Error inflating class ImageView

**Comment by mariantonia** [comment]
Getting the same error

**Comment by rameshfreshworks** [comment]
Hope you were able to solve this issue.
If the problem still persists, Please reach out to us through support@freshchat.com
