### ISSUE TITLE
Provide custom FileProvider to avoid conflicts.

### ISSUE THREAD

**Issue by gnumilanix** [freshworks/freshchat-android#4]
Since Freschat does not provide a default FileProvider, it causes conflicts with anyone using the default one. It can, however, be resolved by adding the following:

```java
package com.freshchat.consumer.provider;

import android.support.v4.content.FileProvider;

/**
 * Extension of {@link FileProvider} that avoids collision with other file providers
 *
 * @author milan
 */
public class FreshchatFileProvider extends FileProvider {
}
```

````xml
<string name="freshchat_file_provider_authority">com.example.demoapp.provider</string>

<provider
    android:name="com.freshchat.consumer.provider.FreshchatFileProvider"
    android:authorities="com.example.demoapp.provider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/freshchat_file_provider_paths" />
</provider>
````

Please add it in the next version of the SDK if possible.

**Comment by tryprasannan** [comment]
Thanks for the suggestion. We considered this approach and chose not to implement this as authority string needs to be unique per app and specifying dynamic field like application id in authority doesn't always play nice with all build systems & tools and end up generating same authority string causing issues. We wanted to avoid this and hence the current approach where the app developer includes the few lines in manifest including the authority string.

**Comment by gnumilanix** [comment]
@tryprasannan I think you have understood me wrong. I am not suggesting to add provider and authority to Freshchat SDK. What I am suggesting however is, to provide a custom FileProvider that developers can add to their app with _just few lines in manifest including the authority string_. Without having to create a custom FileProvider because it conflicts with anyone using the default one.

About for the application id and authority, this should not be an issue with Gradle:
```gradle
def freshchatFileProviderAuthorityPrefix = '.FreshchatFileProvider'

android {
	productFlavors {
		customer {
		    applicationId "com.app.customer"
		    manifestPlaceholders = [freshchatFileProviderAuthority: applicationId + freshchatFileProviderAuthorityPrefix]
		    resValue "string", "freshchat_file_provider_authority", applicationId + freshchatFileProviderAuthorityPrefix
		}
		partner {
		    applicationId "com.app.partner"
		    manifestPlaceholders = [freshchatFileProviderAuthority: applicationId + freshchatFileProviderAuthorityPrefix]
		    resValue "string", "freshchat_file_provider_authority", applicationId + freshchatFileProviderAuthorityPrefix
		}
	}
}
```

And in Manifest.xml
```xml
<provider
    android:name="com.freshchat.consumer.provider.FreshchatFileProvider"
    android:authorities="${freshchatFileProviderAuthority}"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/freshchat_file_provider_paths" />
</provider>
```

**Comment by sagar-viradiya** [comment]
I am also facing same issue where in I am using default file provider and it is conflicting with freshchat provider. Any plan to address this ?

**Comment by wildseansy** [comment]
My team is considering using Freshchat; we have everything setup, but this is a blocker for us.  The fact that this has been open for a year with no one assigned and a clear solution suggested is not very promising.

**Comment by sweetdeath93** [comment]
are there any updates on this issue?

**Comment by jesobreira** [comment]
Any interest to fix this?

**Comment by MuthuFD** [comment]
Hi @jesobreira , If you already have file provider you need not create a new provider for Freshchat.
You can reuse the existing FileProvider for Freshchat.

**Steps to reuse existing FileProvider**
1. Add below line in your strings.xml
```
<string name="freshchat_file_provider_authority">YOUR_PROVIDER_AUTHORITY</string>
```
2. Add below tags in your providers resource xml if they are not already present.
```
    <files-path
        name="int_files"
        path="." />
    <external-files-path
        name="ext_files"
        path="." />
    <cache-path
        name="int_cache"
        path="." />
    <external-cache-path
        name="ext_cache"
        path="." />
```

**Comment by jesobreira** [comment]
Thank you @MuthuFD, it works!

**Comment by MaheshwariSneha27** [comment]
Hi ,

I tried the same solution still I am getting the error

**Comment by MuthuFD** [comment]
@MaheshwariSneha27 Are you also facing provider conflict error?

If not, you can refer this video https://freshchat.wistia.com/medias/qrhrj1vzp1

**Comment by MaheshwariSneha27** [comment]
Hi,
I already had a provider and later on adding freshChat Sdk I got provider error so I added  below code in my existing provider path file

<files-path
        name="int_files"
        path="." />
    <external-files-path
        name="ext_files"
        path="." />
    <cache-path
        name="int_cache"
        path="." />
    <external-cache-path
        name="ext_cache"
        path="." />
________________________________

**Comment by MuthuFD** [comment]
@MaheshwariSneha27 
1. Are you still getting the toast?
2. What is the error?

**Comment by MaheshwariSneha27** [comment]
Hi

I am getting a toast saying "Missing/Bad FileProvider for FreshChat. Camera capture will fail in devices running Nougat or later versions of OS (ErrorCode :354)"

________________________________

**Comment by MuthuFD** [comment]
@MaheshwariSneha27 
Have you added below line in your strings.xml with your provider name?
<string name="freshchat_file_provider_authority">YOUR_PROVIDER_AUTHORITY</string>

**Comment by MaheshwariSneha27** [comment]
Hi,

I have used below code

In Manifest -

<provider
    android:name="androidx.core.content.FileProvider"
    android:authorities="com.vetifly.vetifly.provider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_paths" />

</provider>

In string.xml-

<string name="freshChat_file_provider_authority">com.vetifly.vetifly.provider</string>

In provider path-


<external-path
    name="external_files"
    path="." />
<files-path
    name="int_files"
    path="." />
<external-files-path
    name="ext_files"
    path="." />
<cache-path
    name="int_cache"
    path="." />
<external-cache-path
    name="ext_cache"
    path="." />

________________________________

**Comment by MuthuFD** [comment]
@MaheshwariSneha27 
freshchat_file_provider_authority spelling is wrong. All lower case.
Can you modify that and check again.

**Comment by MaheshwariSneha27** [comment]
Hi,

Changed to authority to

<string name="provider_authority">com.vetifly.vetifly.provider</string>

still getting the error
________________________________

**Comment by MuthuFD** [comment]
@MaheshwariSneha27 
"freshchat_file_provider_authority" is the key. 
You have added just "provider_authority".

**Comment by MaheshwariSneha27** [comment]
Hi,

Thanks It worked now.
________________________________
