### ISSUE TITLE
Request : migrating to AndroidX

### ISSUE THREAD

**Issue by daadu** [freshworks/freshchat-android#49]

**Comment by MuthuFD** [comment]
Hi @daadu , 

Thanks for asking this.

We might not be able to migrate the existing SDK because it might not work for majority of our customer. 

On that note, we will surely look into how we can support customers using AndroidX.

**Comment by daadu** [comment]
@MuthuFD nothing particular. I am using this SDK as Flutter Plugin, check [flutter_freshchat](https://pub.dev/packages/flutter_freshchat), Since I am migrating to AndroidX, flutter requires all plugin to either use AndroidX xor Android.

If existing clients are using Android lib, then I guess can you host a variant with AndroidX? or should I fork this project and host it myself?

**Comment by MuthuFD** [comment]
Hi @daadu,
Flutter plugin looks cool. We would also like to provide a AndroidX variant. But all the moment we will not be able to do it.

Please fork and give it a shot.

If you need any help with documentation or native SDK api queries, feel free to contact us at support@freshchat.com.

**Comment by sanketpatel29** [comment]
> Hi @daadu ,
> 
> Thanks for asking this.
> 
> We might not be able to migrate the existing SDK because it might not work for majority of our customer.
> 
> On that note, we will surely look into how we can support customers using AndroidX.

Please Release with androidX[like 2.8.0] and Existing customers who never updated to androidX ,Let them use older 2.7.0.

**Comment by adibrusydif** [comment]
sorry, Is react-native-freshchat-sdk already support Android X ? @MuthuFD

**Comment by rameshfreshworks** [comment]
yes .. we support with stable versions of AndroidX. Let us know if you face any issue in this regard

**Comment by adibrusydif** [comment]
Thankyou for response my problem @rameshfreshworks 
i have integrating on same version of react-native-freshchat-sdk: 2.0.0
On Apps without Android X : Working
On App with Android X : Not Working

Now Im just checking on my android x apps node_modules/react-native-freshchat-sdk/android/buld.gradle  and i found the com.github.freshdesk:freshchat-android:2.5.2 but your latest is 2.7.1, it is causing the problem? 
<img width="442" alt="Screen Shot 2019-09-11 at 17 55 06" src="https://user-images.githubusercontent.com/29650690/64691760-b27db100-d4bd-11e9-9319-64465bf946e2.png">

**Comment by adibrusydif** [comment]
@rameshfreshworks  btw ,its you?
<img width="1044" alt="Screen Shot 2019-09-11 at 18 00 30" src="https://user-images.githubusercontent.com/29650690/64691944-199b6580-d4be-11e9-833c-7a01004c5104.png">

my team has receive your mail and tried your solution but still cant work

**Comment by rameshfreshworks** [comment]
@adibrusydif Hi .. yeah it's me :).  Our team is looking at the issue, will get back to you shortly.

**Comment by adibrusydif** [comment]
thankyou @rameshfreshworks :)

**Comment by DeMingStrong** [comment]
hello，Is this version now supported AndroidX ,Thank you for your prompt reply

**Comment by DeMingStrong** [comment]
> @adibrusydif嗨..是的，是我:)。我们的小组正在研究该问题，我们会尽快与您联系。

您好，此版本是否现在支持AndroidX，谢谢您的及时答复

**Comment by adibrusydif** [comment]
hello again @rameshfreshworks 
i want to ask something,
Are react-native-freshchat-sdk version 2.6.1 compatible with react native 0.62 ?

**Comment by DeMingStrong** [comment]
I am not very clear, if it is convenient to add my contact information: Telegram (+60 1123836103), we can discuss together




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Adib"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月19日(星期五) 晚上7:13
收件人:&nbsp;"freshdesk/freshchat-android"<freshchat-android@noreply.github.com&gt;;
抄送:&nbsp;"Struggle "<1299185962@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [freshdesk/freshchat-android] Request : migrating to AndroidX (#49)





 
hello again @rameshfreshworks
 i want to ask something,
 Are react-native-freshchat-sdk version 2.6.1 compatible with react native 0.62 ?

**Comment by adibrusydif** [comment]
which version of react-native-freshchat-sdk support on React Native version 0.62 ?

**Comment by DeMingStrong** [comment]
I am using 3.6.0 now, android version is 3.5.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Adib"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月19日(星期五) 晚上7:34
收件人:&nbsp;"freshdesk/freshchat-android"<freshchat-android@noreply.github.com&gt;;
抄送:&nbsp;"Struggle "<1299185962@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [freshdesk/freshchat-android] Request : migrating to AndroidX (#49)





 
which version of react-native-freshchat-sdk support on React Native version 0.62 ?

**Comment by DeMingStrong** [comment]
> React Native版本0.62支持哪个版本的react-native-freshchat-sdk？

What do you use to integrate the SDK

**Comment by MuthuFD** [comment]
Hi All. SDK is using AndroidX dependencies from 4.1.0.
Closing this issue.
