### ISSUE TITLE
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class

### ISSUE THREAD

**Issue by laitooo** [freshworks/freshchat-android#54]
I successfully integrated the api into my app , i wanted to build an apk file but it failed with this very long error

`Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.freshchat.consumer.sdk.activity.ArticleDetailActivity$2) that doesn't come with an
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:this warning is that reflective operations on this class will incorrectly
Error:compiler that did not target the modern .class file format. The recommended
Error:(com.freshchat.consumer.sdk.activity.ArticleDetailActivity$1) that doesn't come with an
Error:this warning is that reflective operations on this class will incorrectly
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:compiler that did not target the modern .class file format. The recommended
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:(com.freshchat.consumer.sdk.a.b$1) that doesn't come with an
Error:(com.freshchat.consumer.sdk.Freshchat$1) that doesn't come with an
Error:indicate that it is *not* an inner class.
Error:(com.freshchat.consumer.sdk.Freshchat$1$1) that doesn't come with an
Error:compiler that did not target the modern .class file format. The recommended
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:(com.freshchat.consumer.sdk.activity.ArticleDetailActivity$2$1$1) that doesn't come with an
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:this warning is that reflective operations on this class will incorrectly
Error:(com.freshchat.consumer.sdk.activity.ArticleDetailActivity$3) that doesn't come with an
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:compiler that did not target the modern .class file format. The recommended
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:this warning is that reflective operations on this class will incorrectly
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:compiler that did not target the modern .class file format. The recommended
Error:indicate that it is *not* an inner class.
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:this warning is that reflective operations on this class will incorrectly
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:compiler that did not target the modern .class file format. The recommended
Error:this warning is that reflective operations on this class will incorrectly
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.freshchat.consumer.sdk.Freshchat$2) that doesn't come with an
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:indicate that it is *not* an inner class.
Error:(com.freshchat.consumer.sdk.activity.ArticleDetailActivity$1$1) that doesn't come with an
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:(com.freshchat.consumer.sdk.activity.ArticleListActivity$1) that doesn't come with an
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:indicate that it is *not* an inner class.
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:(com.freshchat.consumer.sdk.a) that doesn't come with an
Error:this warning is that reflective operations on this class will incorrectly
Error:compiler that did not target the modern .class file format. The recommended
Error:indicate that it is *not* an inner class.
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:(com.freshchat.consumer.sdk.activity.ArticleDetailActivity$4) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.freshchat.consumer.sdk.activity.ArticleListActivity$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
...................`

It runs on device successfully 
but build still fails .

this is my build.gradle
`compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.android.support:design:26.1.0'
    //compile 'com.android.support:support-v4:27.+'
    //compile 'com.android.support:appcompat-v7:26.1.0'
    //compile 'com.android.support:recyclerview-v7:26.1.0'
    compile 'com.github.freshdesk:freshchat-android:2.7.1'
    compile 'com.jakewharton:butterknife:8.5.1'
    //compile 'com.google.firebase:firebase-core:17.2.0'
    compile 'com.google.firebase:firebase-messaging:20.0.0'
    annotationProcessor "com.jakewharton:butterknife-compiler:8.5.1"`

**Comment by rameshfreshworks** [comment]
Hope you were able to solve this issue.
If the problem still persists, Please reach out to us through support@freshchat.com
