### ISSUE TITLE
Keyboard doesn't close on back navigation

### ISSUE THREAD

**Issue by AniruddhaKulk** [freshworks/freshchat-android#80]

**Comment by AniruddhaKulk** [comment]
<img width="438" alt="Screenshot 2020-02-25 at 6 48 05 PM" src="https://user-images.githubusercontent.com/19201033/75250976-a2edec80-57ff-11ea-9861-5448cd4a7ebe.png">

When I click back arrow on this screen, the keyboard should hide. But it's not happening.

**Comment by plotic** [comment]
Guys is there any resolution on this one ? or a workaround ? this is a real blocker and it is affecting react-native as well

**Comment by MuthuFD** [comment]
@plotic @AniruddhaKulk 
We are unable to reproduce this issue.
Are you able to reproduce this in the Sample app provided in this repo?
If you are able to reproduce, please share us the code and steps to reproduce to support@freshchat.com

Attached back navigation working as expected video.
[BackNavigationSample.zip](https://github.com/freshworks/freshchat-android/files/5254975/BackNavigationSample.zip)

**Comment by ahrybuk** [comment]
Hi guys. I also faced with problem about keyboard not closed. I figured out, that problem appears, if activity from which I call chat screen opening have some "windowSoftInputMode" value in Manifest. In my case I start chat from activity, that have "android:windowSoftInputMode="adjustResize|stateHidden" parameter in manifest and keyboard does not hide after chat is closed. When I remove this parameter from manifest bug is not reproduced. Can you please check this issue and fix it as soon, as possible?

**Comment by rameshfreshworks** [comment]
Hope you were able to solve this issue.
If the problem still persists, Please reach out to us through support@freshchat.com
