### ISSUE TITLE
Oops! failed to launch

### ISSUE THREAD

**Issue by shriramchoubey** [freshworks/freshchat-android#82]
I am trying to start freshchat and it shows toast while starting the activity

Oops! failed to launch

**Comment by rameshfreshworks** [comment]
Hi @shriramchoubey, 
Could you provide us more info about where exactly this issue is happening like when using Freshchat.showConversations() or Freshchat.showFAQs() API. Also, suggest checking error logs for more info.

**Comment by shriramchoubey** [comment]
Issue solved I made few changes in react native manifest file to change design

**Comment by shriramchoubey** [comment]
I have another issue how to change the color and fontsize of the chat window action bar in android, I am unable to find any color variable in the documentation or the repository

**Comment by rameshfreshworks** [comment]
@shriramchoubey , Here is the sample style setting to customize actionbar in android.

  ```

   <style name="Theme.Freshchat.SelectedTheme" parent="CustomAppTheme" />
    <style name="CustomAppTheme" parent="Theme.Freshchat.Light.DarkActionBar">
        <item name="actionBarStyle">@style/MyTheme.ActionBarStyle</item>
    </style>

    <style name="MyTheme.ActionBarStyle" parent="@style/Base.Widget.AppCompat.ActionBar.Solid">
        <item name="titleTextStyle">@style/ActionBarTitleText</item>
        <item name="subtitleTextStyle">@style/ActionBarSubTitleText</item>
    </style>

    <style name="ActionBarTitleText" parent="@style/TextAppearance.AppCompat.Widget.ActionBar.Title">
        <item name="android:textColor">your color goes here</item>
        <item name="android:textSize">your text size here </item>

    </style>

    <style name="ActionBarSubTitleText" parent="@style/TextAppearance.AppCompat.Widget.ActionBar.Subtitle">
        <item name="android:textColor">your color goes here </item>
        <item name="android:textSize">your text size here </item>

    </style>
```

**Comment by fitkunal** [comment]
I am getting the same issue after introducing tools:node='replace' in AndroidManifest application tag, Any solutions on this issue appreciated.

**Comment by rameshfreshworks** [comment]
@fitkunal Can you tell us why are you using `tools:node='replace`?  This is required only if you are overriding any components declared in the dependency library manifest like Freshchat SDK.  Ref: https://developer.android.com/studio/build/manifest-merge for more info.

**Comment by fitkunal** [comment]
@rameshfreshworks Because I have integrated Zoom SDK and was facing Manifest merge issues which led me to this solution. But now my Freshchat is not working with error message in toast.

**Comment by fitkunal** [comment]
@rameshfreshworks I have solved this issue by looking in Merger failed log. 
Followed the suggestions and steps and Freshchat works completely fine now
