### ISSUE TITLE
IOS app hangs 

### ISSUE THREAD

**Issue by shriramchoubey** [freshworks/freshchat-android#83]
On Calling           
 
Freshchat.setUser(freshchatUser, (error) => {
                console.log(error);
            });

Ios application hangs,
do I have to make in ios files seprately, currently I have not put any notifications code in the freschat is it the reason.

**Comment by shriramchoubey** [comment]
import React, { Component } from 'react'
import { View, StyleSheet, Image, Button } from 'react-native'
import { Freshchat, FreshchatConfig, FreshchatUser,FreshchatMessage, ConversationOptions,FaqOptions } from 'react-native-freshchat-sdk';
export default class App extends Component {
    constructor(props) {
        super(props)
    }

    componentDidMount() {
        var freshchatConfig = new FreshchatConfig("<APP_ID>", "<APP_KEY>");


        Platform.OS === 'ios' ?
        freshchatConfig.showNotificationBanner = false:null //iOS only
        Platform.OS === 'ios' ?
        freshchatConfig.notificationSoundEnabled = true:null //iOS only
        Platform.OS === 'ios' ?
        freshchatConfig.themeName = "CustomTheme.plist":null  //iOS only
        Platform.OS === 'ios' ?
        freshchatConfig.stringsBundle = "FCCustomLocalizable":null //iOS only
        Platform.OS === 'ios' ?
        freshchatConfig.domain = "msdk.in.freshchat.com":null
 

        Freshchat.init(freshchatConfig);

       
    }

  

    render() {

        console.log("---------------start---------------")

        var freshchatUser = new FreshchatUser();
        freshchatUser.firstName = "ram";
        freshchatUser.lastName = "ss";
        freshchatUser.email = "rama@gmail.man";
        freshchatUser.phoneCountryCode = "+91";
        freshchatUser.phone = "9893601266";
        var external_id = "ram"

        //restore id is retrieved by listner when user send first message
        var restoreId = null
        

        if (restoreId === null){
                Freshchat.setUser(freshchatUser, (error) => {
                    console.log(error);
                });
                console.log("set user done")
                
                var userPropertiesJson = {
                    "user_type": "Paid",
                    "plan": "Gold"
                }
                Freshchat.setUserProperties(userPropertiesJson, (error) => {
                    console.log(error);
                });
           
                console.log("set user properties done")


                Freshchat.identifyUser(external_id, null, (error) => {
                    console.log(error);
                });

                console.log("identify user done")


                Freshchat.getUser((user) => {
                    var restore = user.restoreId;
                    console.log("INSIDE: restoreId: " + restore);
                })

                console.log("get restore ID done")

        }
        
        else{

                Freshchat.getUser((user) => {
                    var restore = user.restoreId;
                    console.log("INSIDE: restoreId: " + restore);
                })

                Freshchat.identifyUser(external_id, restoreId, (error) => {
                    console.log(error);
                });
        }

        Freshchat.addEventListener(
            Freshchat.EVENT_USER_RESTORE_ID_GENERATED,
            () => {
                console.log("onRestoreIdUpdated triggered");
                Freshchat.getUser((user) => {
                    var restoreId = user.restoreId;
                    var externalId = user.externalId;
                    console.log("----------------------------------")
                    console.log("externalId: " + externalId);
                    console.log("restoreId: " + restoreId);
                    console.log("----------------------------------")
                })
            }
        );

        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
            <Button
                        title=" Start Customer Support "
                        onPress={() => Freshchat.showConversations()}
                    />
            </View>
        )
    }
}
const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    imageStyle: {
        width: "100%",
        height: "100%"
    }
})

**Comment by muthukrishnan-suresh** [comment]
@shriramchoubey Can you share the payload of `freshchatUser` object?

**Comment by MuthuFD** [comment]
@shriramchoubey Got payload from your second message.
Can you explain what you mean by hangs? Continuous loading or app freeze? 

You can share a gif or video.

**Comment by shriramchoubey** [comment]
var freshchatUser = new FreshchatUser();
    freshchatUser.firstName = "jon";
    freshchatUser.lastName = "ss";
    freshchatUser.email = "jon@gmail.man";
    freshchatUser.phoneCountryCode = "+91";
    freshchatUser.phone = "1111111111

**Comment by shriramchoubey** [comment]
It is because after init if i call any Freshchat object function app stopped working like setUser, getUser, identifyUser, addEventlistner 

But app work if directly called Freshchat.showConversations() 

And user can not be identified in Freshchat customer support portal.

Is there any changes to be made in podspec
 react-native v:60.0
freshdesksdk v:2.3.1

Above i posted my whole code @MuthuFD ,

**Comment by rameshfreshworks** [comment]
Hope you were able to solve this issue.
If the problem still persists, Please reach out to us through support@freshchat.com
