### ISSUE TITLE
Multiple events from Broadcast Intent

### ISSUE THREAD

**Issue by angelix** [freshworks/freshchat-android#88]
Registering the receiver with the following code, when a new message is received, the receiver is called two times. This happens for every new message, and if you have a getUnreadCountAsync method attached to the event, multiple execution of the method occurs.

```
IntentFilter intentFilter = new IntentFilter(Freshchat.FRESHCHAT_UNREAD_MESSAGE_COUNT_CHANGED);
            LocalBroadcastManager.getInstance(this).registerReceiver(unreadCountChangeReceiver, intentFilter);
```

**Comment by rameshfreshworks** [comment]
Can you tell us about where you are registering this receiver in your application?

**Comment by rameshfreshworks** [comment]
@angelix Hope the issue is resolved. Feel free to reopen if the issue still persists.
