### ISSUE TITLE
integration with xamarin forms

### ISSUE THREAD

**Issue by ur3an0** [freshworks/freshchat-android#90]
Hi, i am tray in integrate via xamarin forms using java bindings, but when make config, lauch an exception, meybe u know this issue.

thanks!

![imagen](https://user-images.githubusercontent.com/1440851/84735304-2c712800-af71-11ea-8048-aa77fe946f2f.png)

![imagen](https://user-images.githubusercontent.com/1440851/84735224-f2a02180-af70-11ea-99ea-d7155e7f8b65.png)

![imagen](https://user-images.githubusercontent.com/1440851/84735240-02b80100-af71-11ea-8a30-5646360dddab.png)

**Comment by ur3an0** [comment]
some body?

**Comment by rameshfreshworks** [comment]
Hi @ur3an0, Sorry about the delay in response.  Were you able to solve this issue?

**Comment by MuthuFD** [comment]
@ur3an0 I hope you were able to resolve this. I'm closing the issue. 
If you are still facing this issue, feel free to reopen or contact us at support@freshchat.com
