### ISSUE TITLE
Tapping on the notification doesn't work.

### ISSUE THREAD

**Issue by KamathVishak96** [freshworks/freshchat-android#91]
I have followed the Integration steps related to FCM. I'm getting the notifications, but when I tap on it simply does nothing. When the app is killed, and I tap on the notification it doesn't even open the app. I checked the logs when I tap on the notification and this is the only thing logged.
`D/FRESHCHAT: FreshchatReceiver::onReceive() called`

**Comment by rameshfreshworks** [comment]
Let us know if the issue was resolved. Close it if resolved.

**Comment by KamathVishak96** [comment]
Had contacted Freshworks support. 
Removing `setNotificationInterceptionEnabled(true)` as suggested helped solve the issue.
