### ISSUE TITLE
App is crashing while opening freshchat

### ISSUE THREAD

**Issue by iamaravindh** [freshworks/freshchat-android#93]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String com.freshchat.consumer.sdk.beans.Channel.getName()' on a null object reference
com.freshchat.consumer.sdk.a.c.getView

**Comment by MuthuFD** [comment]
@iamaravindh Are you on the latest version of Freshchat SDK?

**Comment by rameshfreshworks** [comment]
This issue is fixed in version 3.6.0. Update to latest version of freshchat if not already done.
