### ISSUE TITLE
event to stop loading widget

### ISSUE THREAD

**Issue by vaasav-kumar** [freshworks/freshchat-android#96]
Assume i have initiated freshchat , but in some case i need to stop loading freshchat.
Is there any way to prevent it ?

**Comment by rameshfreshworks** [comment]
Hi @vaasav-kumar , are you using android SDK? can you explain a bit more about your usecase?

**Comment by rameshfreshworks** [comment]
Closing due to no response. @vaasav-kumar Feel free to reopen with details if the issue is not resolved.
