### ISSUE TITLE
Request: upgrade dependency of Picasso to latest version 

### ISSUE THREAD

**Issue by developerjohan01** [freshworks/freshchat-android#97]
Hi, would you consider updating the dependency on Picasso to the latest version?
I know the latest version (Version 2.71828) is not fully backwards compatible with 2.5.2 but it has been available since 2018-03-07 and it is apparently compatible with coming versions (3.0) 

This is from the square/picasso [changelog](https://github.com/square/picasso/blob/master/CHANGELOG.md)
> This version is not fully backwards compatible with previous 2.x releases! It is intended to be a stable, pre-3.0 release that users of 3.0.0-SNAPSHOT can use in the mean time.

### Motivation 
Upgrading means that it becomes easier to use the FreshChat out of the box since it will avoid potential conflicts with other libraries using Picasso.: It is unlikely that new usage of the Picasso library will use version 2.5.2 from 2015-03-20.  
There is a workaround but If you always have to use it, it isn't a workaround but required setup.

Another motivation is that freshchat-android is used in various plugins. For example in Cordova/phone-gap and Ionic and you normally don't want to make setup changes via code like the existing [workaround (section 8.2)](https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps). 

Also, see issues #52 #46 etc

**Comment by abdullahizzuddiin** [comment]
Hi, have you found any solution?

**Comment by tasomaniac** [comment]
We are also having similiar issue since we upgraded couple of Firebase libraries and they depend on the newer version of Picasso already.

Picasso also should be updated so that Freshchat does not depend on deprecated Android Support libraries anymore. It is a good step forward. Users can disable Jettifier in their projects so that their builds are slightly faster.

**Comment by rameshfreshworks** [comment]
The stars have aligned and we have good news :)
We have upgraded Picasso library to latest version which is 2.8.  This change is live in latest release [4.3.3](https://github.com/freshworks/freshchat-android/releases/tag/4.3.3).
